codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default:
        target: 95%
        threshold: 2%
    patch:
      default:
        informational: true

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default

flags:
  unittests:
    paths:
      - src/spartan/
    carryforward: true
